services:
  db:
    image: postgres:16
    container_name: notes_db
    environment:
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
      POSTGRES_DB: notes
    ports:
      - '5432:5432'
    volumes:
      - notes_pg:/var/lib/postgresql/data

volumes:
  notes_pg:
